### ISSUE TITLE
Debug the indexer's DB connectivity issues

### ISSUE THREAD

**Issue by carterqw2** [celo-org/blockscout#193]
**Description**
Under load the indexer starts dropping DB tasks, that looks like this in the logs:
```
"Task #PID<0.2485.14> started from Indexer.Fetcher.CeloValidatorHistory terminating
** (DBConnection.ConnectionError) connection not available and request was dropped from queue after 1634ms. You can configure how long requests wait in the queue using :queue_target and :queue_interval. See DBConnection.start_link/2 for more information
    (db_connection) lib/db_connection.ex:836: DBConnection.transaction/3
    (ecto) lib/ecto/repo/transaction.ex:15: Ecto.Repo.Transaction.transaction/4
    (stdlib) timer.erl:197: :timer.tc/3
    (explorer) lib/explorer/repo.ex:21: anonymous fn/2 in Explorer.Repo.logged_transaction/2
    (explorer) lib/explorer/logger.ex:14: Explorer.Logger.metadata/2
    (explorer) lib/explorer/chain/import.ex:319: anonymous fn/3 in Explorer.Chain.Import.import_transactions/2
    (elixir) lib/enum.ex:3325: Enumerable.List.reduce/3
    (elixir) lib/enum.ex:1998: Enum.reduce_while/3
    (explorer) lib/explorer/chain/import.ex:318: Explorer.Chain.Import.import_transactions/2
    (explorer) lib/explorer/logger.ex:14: Explorer.Logger.metadata/2
    (explorer) lib/explorer/chain/import.ex:128: Explorer.Chain.Import.all/1
    (indexer) lib/indexer/fetcher/celo_validator_history.ex:175: Indexer.Fetcher.CeloValidatorHistory.import_items/1
    (indexer) lib/indexer/fetcher/celo_validator_history.ex:56: Indexer.Fetcher.CeloValidatorHistory.run/2
    (elixir) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (elixir) lib/task/supervised.ex:35: Task.Supervised.reply/5
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Function: &Indexer.BufferedTask.log_run/1
    Args: [%{batch: [%{block_number: 5098927, retries_count: 0}], callback_module: Indexer.Fetcher.CeloValidatorHistory, callback_module_state: {0, []}, metadata: []}]"
```
Usually there are CPU spikes on CloudSQL proxy sidecar container, although there are normal level of db CPU utilization and a reasonable number of connections.

When the indexer cannot recover from these errors for 5 minutes (and the health check endpoint cannot establish connection to the db as well), the container is restarted which leads to a number of pending transactions that get stuck in this status.

**Acceptance Criteria**
We have a good hypothesis on why this might be happening and there is a plan of actions how to reduce the number of these issues.

**Comment by carterqw2** [comment]
Here is the ticket that describes the issue:
https://app.zenhub.com/workspaces/web-services-sprint-60103a7bf450290020c3800c/issues/celo-org/blockscout/213
