### ISSUE TITLE
Issues with RPC calls to read replicas

### ISSUE THREAD

**Issue by carterqw2** [celo-org/blockscout#289]
Issues with RPC queries on read replicas:
```
Error while calling RPC action"** (Plug.Conn.WrapperError) ** (Postgrex.Error) FATAL 40001 (serialization_failure) terminating connection due to conflict with recovery\n\n    hint: In a moment you should be able to reconnect to the database and repeat your command.\n\nUser query might have needed to see row versions that must be removed.\n    (ecto_sql 3.6.1) lib/ecto/adapters/sql.ex:749: Ecto.Adapters.SQL.raise_sql_call_error/1\n    (ecto_sql 3.6.1) lib/ecto/adapters/sql.ex:682: Ecto.Adapters.SQL.execute/5\n    (ecto 3.6.1) lib/ecto/repo/queryable.ex:224: Ecto.Repo.Queryable.execute/4\n    (ecto 3.6.1) lib/ecto/repo/queryable.ex:19: Ecto.Repo.Queryable.all/3\n    (block_scout_web 0.0.1) lib/block_scout_web/controllers/api/rpc/token_controller.ex:169: BlockScoutWeb.API.RPC.TokenController.list_token_transfers/1\n    (block_scout_web 0.0.1) lib/block_scout_web/controllers/api/rpc/token_controller.ex:28: BlockScoutWeb.API.RPC.TokenController.tokentx/2\n    (block_scout_web 0.0.1) lib/block_scout_web/controllers/api/rpc/token_controller.ex:1: BlockScoutWeb.API.RPC.TokenController.action/2\n    (block_scout_web 0.0.1) lib/block_scout_web/controllers/api/rpc/token_controller.ex:1: BlockScoutWeb.API.RPC.TokenController.phoenix_controller_pipeline/2\n"
```

Failing request:
```
SELECT t2."token_contract_address_hash", t2."transaction_hash", t2."from_address_hash", t2."to_address_hash", t2."amount", b0."timestamp", t1."index", l3."index", l3."data", l3."first_topic", l3."second_topic", l3."third_topic", l3."fourth_topic", t1."block_number", t1."gas_price", t1."gas_currency_hash", t1."gas_fee_recipient_hash", t1."gas_used", t1."gateway_fee" FROM "blocks" AS b0 LEFT OUTER JOIN "transactions" AS t1 ON t1."block_number" = b0."number" LEFT OUTER JOIN "token_transfers" AS t2 ON t2."transaction_hash" = t1."hash" LEFT OUTER JOIN "logs" AS l3 ON ((l3."transaction_hash" = t1."hash") AND (l3."address_hash" = $1)) AND (l3."index" = t2."log_index") WHERE (((b0."number" >= $2) AND (b0."number" <= $3)) AND (t2."token_contract_address_hash" = $4)) ORDER BY t2."block_number", t1."index"
```

Another RPC call:
```
Error while calling RPC action"** (Plug.Conn.WrapperError) ** (DBConnection.ConnectionError) connection not available and request was dropped from queue after 1186ms. This means requests are coming in and your connection pool cannot serve them fast enough. You can address this by:\n\n  1. Ensuring your database is available and that you can connect to it\n  2. Tracking down slow queries and making sure they are running fast enough\n  3. Increasing the pool_size (albeit it increases resource consumption)\n  4. Allowing requests to wait longer by increasing :queue_target and :queue_interval\n\nSee DBConnection.start_link/2 for more information\n\n    (ecto_sql 3.6.1) lib/ecto/adapters/sql.ex:749: Ecto.Adapters.SQL.raise_sql_call_error/1\n    (ecto_sql 3.6.1) lib/ecto/adapters/sql.ex:682: Ecto.Adapters.SQL.execute/5\n    (ecto 3.6.1) lib/ecto/repo/queryable.ex:224: Ecto.Repo.Queryable.execute/4\n    (ecto 3.6.1) lib/ecto/repo/queryable.ex:19: Ecto.Repo.Queryable.all/3\n    (ecto 3.6.1) lib/ecto/repo/queryable.ex:159: Ecto.Repo.Queryable.one!/3\n    (explorer 0.0.1) lib/explorer/chain.ex:2550: Explorer.Chain.max_consensus_block_number/0\n    (explorer 0.0.1) lib/explorer/etherscan.ex:45: Explorer.Etherscan.list_transactions/2\n    (block_scout_web 0.0.1) lib/block_scout_web/controllers/api/rpc/address_controller.ex:477: BlockScoutWeb.API.RPC.AddressController.list_transactions/2\n" 
```

**Comment by carterqw2** [comment]
Happens only under load, so expected.
