### ISSUE TITLE
Error fetching token balance

### ISSUE THREAD

**Issue by carterqw2** [celo-org/blockscout#358]
**How to reproduce**
1. Open https://explorer.celo.org/address/0x5D2238753F3ca5E649f9250C303d5c196A069F24/transactions
2. Notice the error
![image.png](https://images.zenhubusercontent.com/5fb299ab87bffe6be1329686/40c39908-6a87-4394-b46c-5be55bec0cfb)

**Logs**
https://cloudlogging.app.goo.gl/8Zq19guduDmv7ceA8
```
"Task #PID<0.24840.0> started from #PID<0.24839.0> terminating
** (KeyError) key :token_type not found in: %Explorer.Chain.Address.CurrentTokenBalance{__meta__: #Ecto.Schema.Metadata<:loaded, "address_current_token_balances">, address: #Ecto.Association.NotLoaded<association :address is not loaded>, address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<117, 230, 95, 82, 8, 114, 109, 150, 255, 148, 80, 239, 88, 44, 168, 240, 237, 38, 71, 131>>}, block_number: 8347049, id: 105122443, inserted_at: ~U[2021-06-23 17:43:39.036771Z], old_value: #Decimal<49999914270000000000>, token: %Explorer.Chain.Token{__meta__: #Ecto.Schema.Metadata<:loaded, "tokens">, bridged: nil, cataloged: true, contract_address: #Ecto.Association.NotLoaded<association :contract_address is not loaded>, contract_address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<71, 30, 206, 55, 80, 218, 35, 127, 147, 184, 227, 57, 197, 54, 152, 155, 137, 120, 164, 56>>}, decimals: #Decimal<18>, holder_count: 285239, inserted_at: ~U[2021-02-02 16:31:59.783537Z], name: "Celo native asset", symbol: "CELO", total_supply: #Decimal<629198437725349809925717199>, type: "ERC-20", updated_at: ~U[2021-08-19 14:29:57.600716Z]}, token_contract_address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<71, 30, 206, 55, 80, 218, 35, 127, 147, 184, 227, 57, 197, 54, 152, 155, 137, 120, 164, 56>>}, updated_at: ~U[2021-08-18 18:41:18.367017Z], value: #Decimal<49999914270000000000>, value_fetched_at: ~U[2021-08-18 18:41:18.362031Z]}
    (indexer 0.1.0) lib/indexer/fetcher/token_balance_on_demand.ex:68: anonymous fn/3 in Indexer.Fetcher.TokenBalanceOnDemand.fetch_and_update/3
    (elixir 1.11.4) lib/enum.ex:1411: Enum."-map/2-lists^map/1-0-"/2
    (indexer 0.1.0) lib/indexer/fetcher/token_balance_on_demand.ex:51: Indexer.Fetcher.TokenBalanceOnDemand.fetch_and_update/3
    (indexer 0.1.0) lib/indexer/fetcher/token_balance_on_demand.ex:40: Indexer.Fetcher.TokenBalanceOnDemand.do_trigger_fetch/4
    (elixir 1.11.4) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (stdlib 3.14.1) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Function: #Function<1.27585641/0 in BlockScoutWeb.AddressTokenBalanceController.index/2>
    Args: []"
```
```
"#PID<0.11410.0> running BlockScoutWeb.Endpoint (connection #PID<0.10377.0>, stream id 6) terminated
Server: explorer.celo.org:80 (http)
Request: GET /address/0x5D2238753F3ca5E649f9250C303d5c196A069F24/token-balances
** (exit) an exception was raised:
    ** (FunctionClauseError) no function clause matching in Gettext.dgettext/4
        (gettext 0.16.1) lib/gettext.ex:669: Gettext.dgettext(BlockScoutWeb.Gettext, "default", nil, %{})
        (block_scout_web 0.0.1) lib/block_scout_web/templates/address_token_balance/_tokens.html.eex:39: anonymous fn/3 in BlockScoutWeb.AddressTokenBalanceView."_tokens.html"/1
        (elixir 1.11.4) lib/enum.ex:2193: Enum."-reduce/3-lists^foldl/2-0-"/3
        (block_scout_web 0.0.1) lib/block_scout_web/templates/address_token_balance/_tokens.html.eex:6: BlockScoutWeb.AddressTokenBalanceView."_tokens.html"/1
        (block_scout_web 0.0.1) lib/block_scout_web/templates/address_token_balance/_token_balances.html.eex:49: BlockScoutWeb.AddressTokenBalanceView."_token_balances.html"/1
        (phoenix 1.5.6) lib/phoenix/view.ex:472: Phoenix.View.render_to_iodata/3
        (phoenix 1.5.6) lib/phoenix/controller.ex:776: Phoenix.Controller.render_and_send/4
        (block_scout_web 0.0.1) lib/block_scout_web/controllers/address_token_balance_controller.ex:1: BlockScoutWeb.AddressTokenBalanceController.action/2"
```

**Comment by rkachowski** [comment]
likely due to https://github.com/blockscout/blockscout/commit/e581668a8ff9fa431fc9b1894801569327dfe69e

```
          %{}
          |> Map.put(:address_hash, stale_current_token_balance.address_hash)
          |> Map.put(:token_contract_address_hash, stale_current_token_balance.token_contract_address_hash)
          |> Map.put(:token_type, stale_current_token_balance.token_type)
          |> Map.put(:block_number, block_number)
```

The error implies that `stale_current_token_balance` is of type `Explorer.Chain.Address.CurrentTokenBalance` which does not have a `token_type` field.
