### ISSUE TITLE
Address transaction missing error when ingesting events

### ISSUE THREAD

**Issue by rkachowski** [celo-org/blockscout#564]
# Summary

There appear to be two events that cannot be inserted into the database due to missing transaction hashes. These events are retried every 3 seconds or so resulting in skewed error metrics that trigger alerting. 

# Blockscout links

```
Could not insert all of chunk into Elixir.Explorer.Chain.CeloContractEvent using options because of error.

Chunk Size: 1
Chunk:

[%{block_hash: %Explorer.Chain.Hash{byte_count: 32, bytes: <<176, 55, 32, 131, 152, 17, 202, 34, 82, 220, 237, 29, 157, 174, 59, 98, 205, 89, 220, 98, 213, 34, 190, 122, 217, 20, 103, 255, 95, 102, 103, 92>>}, contract_address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<141, 102, 119, 25, 33, 68, 41, 40, 112, 144, 126, 63, 168, 165, 82, 127, 229, 90, 127, 246>>}, inserted_at: ~U[2022-02-20 17:39:35.830456Z], log_index: 2, name: "ValidatorGroupActiveVoteRevoked", params: %{account: "\\x26976629e5982f1f160d3af249b15f95761affd1", group: "\\x6f8e6ff69935f000b09d182a4739342faeaf0c77", units: 17587259925777467233886194742728325905330, value: 192721293087749306830}, transaction_hash: %Explorer.Chain.Hash{byte_count: 32, bytes: <<209, 193, 125, 203, 14, 127, 79, 183, 173, 182, 135, 73, 184, 201, 255, 224, 126, 119, 247, 177, 132, 163, 36, 222, 164, 38, 146, 169, 224, 213, 147, 120>>}, updated_at: ~U[2022-02-20 17:39:35.830456Z]}]

Options:

[conflict_target: [:block_hash, :log_index], on_conflict: :nothing, returning: true, timeout: 60000, timestamps: %{inserted_at: ~U[2022-02-20 17:39:35.830456Z], updated_at: ~U[2022-02-20 17:39:35.830456Z]}]

Exception:

** (Postgrex.Error) ERROR 23503 (foreign_key_violation) insert or update on table "celo_contract_events" violates foreign key constraint "transaction_hash"

    table: celo_contract_events
    constraint: transaction_hash

Key (transaction_hash)=(\xd1c17dcb0e7f4fb7adb68749b8c9ffe07e77f7b184a324dea42692a9e0d59378) is not present in table "transactions".
    (ecto_sql 3.7.0) lib/ecto/adapters/sql.ex:756: Ecto.Adapters.SQL.raise_sql_call_error/1
    (ecto_sql 3.7.0) lib/ecto/adapters/sql.ex:663: Ecto.Adapters.SQL.insert_all/9
    (ecto 3.7.1) lib/ecto/repo/schema.ex:58: Ecto.Repo.Schema.do_insert_all/7
    (explorer 0.0.1) lib/explorer/repo.ex:61: anonymous fn/5 in Explorer.Repo.safe_insert_all/3
    (elixir 1.12.3) lib/enum.ex:2385: Enum."-reduce/3-lists^foldl/2-0-"/3
    (explorer 0.0.1) lib/explorer/chain/import.ex:299: Explorer.Chain.Import.insert_changes_list/3
    (explorer 0.0.1) lib/explorer/chain/import/runner/celo_contract_event.ex:53: Explorer.Chain.Import.Runner.CeloContractEvent.insert/3
    (ecto 3.7.1) lib/ecto/multi.ex:716: Ecto.Multi.apply_operation/5
```

* https://explorer.celo.org/tx/0xd1c17dcb0e7f4fb7adb68749b8c9ffe07e77f7b184a324dea42692a9e0d59378/internal-transactions

```
Could not insert all of chunk into Elixir.Explorer.Chain.CeloContractEvent using options because of error.

Chunk Size: 1
Chunk:

[%{block_hash: %Explorer.Chain.Hash{byte_count: 32, bytes: <<181, 141, 189, 104, 183, 241, 232, 11, 111, 61, 139, 231, 200, 196, 97, 130, 160, 254, 38, 195, 137, 114, 83, 46, 136, 179, 93, 33, 220, 130, 90, 231>>}, contract_address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<141, 102, 119, 25, 33, 68, 41, 40, 112, 144, 126, 63, 168, 165, 82, 127, 229, 90, 127, 246>>}, inserted_at: ~U[2022-02-20 17:39:35.796479Z], log_index: 10, name: "ValidatorGroupVoteActivated", params: %{account: "\\x5557d17c79cbefdddaf4030a7f5fccd09be90823", group: "\\x7c75b0b81a54359e9dccda9cb663ca2e3de6b710", units: 11396315742826694923454148424213292754940, value: 124999938602500001794}, transaction_hash: %Explorer.Chain.Hash{byte_count: 32, bytes: <<15, 96, 95, 44, 79, 114, 65, 144, 233, 113, 97, 81, 12, 71, 55, 114, 110, 67, 209, 17, 210, 105, 187, 176, 37, 105, 102, 160, 121, 190, 214, 239>>}, updated_at: ~U[2022-02-20 17:39:35.796479Z]}]

Options:

[conflict_target: [:block_hash, :log_index], on_conflict: :nothing, returning: true, timeout: 60000, timestamps: %{inserted_at: ~U[2022-02-20 17:39:35.796479Z], updated_at: ~U[2022-02-20 17:39:35.796479Z]}]

Exception:

** (Postgrex.Error) ERROR 23503 (foreign_key_violation) insert or update on table "celo_contract_events" violates foreign key constraint "transaction_hash"

    table: celo_contract_events
    constraint: transaction_hash

Key (transaction_hash)=(\x0f605f2c4f724190e97161510c4737726e43d111d269bbb0256966a079bed6ef) is not present in table "transactions".
    (ecto_sql 3.7.0) lib/ecto/adapters/sql.ex:756: Ecto.Adapters.SQL.raise_sql_call_error/1
    (ecto_sql 3.7.0) lib/ecto/adapters/sql.ex:663: Ecto.Adapters.SQL.insert_all/9
    (ecto 3.7.1) lib/ecto/repo/schema.ex:58: Ecto.Repo.Schema.do_insert_all/7
    (explorer 0.0.1) lib/explorer/repo.ex:61: anonymous fn/5 in Explorer.Repo.safe_insert_all/3
    (elixir 1.12.3) lib/enum.ex:2385: Enum."-reduce/3-lists^foldl/2-0-"/3
    (explorer 0.0.1) lib/explorer/chain/import.ex:299: Explorer.Chain.Import.insert_changes_list/3
    (explorer 0.0.1) lib/explorer/chain/import/runner/celo_contract_event.ex:53: Explorer.Chain.Import.Runner.CeloContractEvent.insert/3
    (ecto 3.7.1) lib/ecto/multi.ex:716: Ecto.Multi.apply_operation/5
```

* https://explorer.celo.org/tx/0x0f605f2c4f724190e97161510c4737726e43d111d269bbb0256966a079bed6ef/logs

# To Do

* Investigate why this happens
   * Blockscout has indexed these transactions - they clearly exist
* address issue
* reset error threshold on https://console.cloud.google.com/monitoring/alerting/policies/11296981364095360920?project=celo-testnet-production
    * was initially 32

**Comment by rkachowski** [comment]
It appears this issue affects only rc1-3 and is preventing two blocks from being inserted into the db 

* https://rc1-blockscout3.celo-testnet.org/block/11550526/transactions
* https://rc1-blockscout3.celo-testnet.org/block/11525844/transactions

https://console.cloud.google.com/logs/query;cursorTimestamp=2022-02-18T18:11:00.245Z;query=resource.type%3D%22k8s_container%22%0Aseverity%3DERROR%0Aresource.labels.container_name%20%3D~%20%22blockscout%22%0Aresource.labels.cluster_name%3D%22mainnet%22%0Atimestamp%3D%222022-02-18T18:11:00.245Z%22%0AinsertId%3D%22jv07qvoh9xlddgzy%22;summaryFields=:false:32:beginning;timeRange=P7D?project=celo-testnet-production
